name: image-uploader
services:
- name: web
  source_dir: /
  github:
    repo: YOUR_GITHUB_USERNAME/image-uploader
    branch: main
    deploy_on_push: true
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /api/user
  env:
  - key: NODE_ENV
    value: "production"
  - key: PORT
    value: "8080"
  - key: SESSION_SECRET
    value: "${SESSION_SECRET}"
    type: SECRET
  - key: DATABASE_PATH
    value: "/app/database/app.db"
  - key: UPLOAD_PATH
    value: "/app/uploads"

databases:
- name: image-uploader-db
  engine: PG
  version: "14"
  size: db-s-dev-database

static_sites: []

jobs: []

workers: []